const state={dogs:[],query:'',puppies:false,withPhoto:false};
const $=id=>document.getElementById(id);
function fmtDate(iso){try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(iso));}catch{return iso||'Unknown';}}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function isPuppy(d){return /(mos?|months?|puppy|puppies)/i.test(`${d.age} ${d.description}`) && !/yr/i.test(d.age||'');}
function filtered(){const q=state.query.toLowerCase();return state.dogs.filter(d=>{const blob=Object.values(d).join(' ').toLowerCase();return (!q||blob.includes(q))&&(!state.puppies||isPuppy(d))&&(!state.withPhoto||!!d.image);});}
function render(){const dogs=filtered();$('dogCount').textContent=state.dogs.length;$('empty').hidden=dogs.length>0; $('dogs').innerHTML=dogs.map(d=>`<article class="dog"><div class="photo" role="img" aria-label="${esc(d.name)}" style="background-image:url('${esc(d.image||'')}')"><span class="badge">${esc(d.distanceMiles??'')} mi · ${esc(d.city||'Bay Area')}</span></div><div class="dog-body"><h2>${esc(d.name)}</h2><p class="meta">${esc([d.breed,d.sex,d.age].filter(Boolean).join(' · '))}</p><div class="chips">${[d.color,d.size,d.shelterName].filter(Boolean).slice(0,3).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><p class="desc">${esc(d.description||'No description yet — check the source listing for more details.')}</p></div><div class="actions"><a class="button primary" href="${esc(d.url)}">View listing</a>${d.contactPhone?`<a class="button secondary" href="tel:${esc(d.contactPhone)}">Call shelter</a>`:''}</div></article>`).join('');}
async function init(){const res=await fetch('./data/dogs.json?v='+Date.now(),{cache:'no-store'}); const data=await res.json(); state.dogs=data.dogs||[]; $('updatedAt').textContent='Updated '+fmtDate(data.updatedAt); $('sources').innerHTML=(data.sources||[]).map(s=>`<div class="source"><a href="${esc(s.url)}">${esc(s.name)}</a><p>${esc(s.status||'')}</p></div>`).join(''); render();}
$('searchBox').addEventListener('input',e=>{state.query=e.target.value;render();}); $('puppyToggle').addEventListener('change',e=>{state.puppies=e.target.checked;render();}); $('withPhotoToggle').addEventListener('change',e=>{state.withPhoto=e.target.checked;render();});
init().catch(err=>{console.error(err);$('updatedAt').textContent='Could not load dog data';});
